apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qa-bkei
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/x6xih2sdzstjcwna4xnhfwyqru"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qa-bked
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/fslejjfdbkkor2cpn7kfxa2hua"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-bkei
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/p3prcq4ibc4ped7hhace22uv7a"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-bked
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/kmvnborkdzg2xrq5y5hayglrse"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dr-bkei
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/li75xnokbtcydhq6cozgb4a6z4"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dr-bked
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/fslejjfdbkkor2cpn7kfxa2hua"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: voutil2
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/76f7tmosycmk6uugpmiom6qrru"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qa-voutil2
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/76cr3vgu23zupmx4nlqtyvwc6y"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dr-voutil2
spec:
  itemPath: "vaults/ozxznermh2dq4gbh55do65oq7e/items/22oeitbsmcfmjxz2mx453mbf7e"