name: Deploy Query server to DR
on:
  release:
    types: [released]

jobs:
  PROD_K8S_Query:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 #v4.0.0
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: https://secretsvault.apps.brown.edu
          OP_CONNECT_TOKEN: ${{ secrets.VO_AUTOMATION_CONNECT_TOKEN }}
          DR_BKEI: op://ozxznermh2dq4gbh55do65oq7e/li75xnokbtcydhq6cozgb4a6z4/dr-bkei.yaml
          ROBOT_DR: op://ozxznermh2dq4gbh55do65oq7e/arbb4qgu676q7evi4u2ubfqiuy/password
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0
      -
        name: pull kubeconfig
        run: |
          mkdir -p secrets
          echo "$DR_BKEI" > secrets/dr-bkei.yaml
          echo "$DR_BKED" > secrets/dr-bked.yaml
          echo -n "$ROBOT_DR" > secrets/robot-dr.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build DR image
        run: make build
      -
        name: Push DR image
        run: make push.dr
      -
        name: Deploy DR app
        run: make deploy.dr
