name: Deploy Query server to PROD
on:
  release:
    types: [released]

jobs:
  PROD_K8S_Query:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.20.0
      -
        name: Build PROD image
        run: make build
      -
        name: Push PROD image
        run: make push.prod
      -
        name: Deploy PROD app
        run: make deploy.prod
