name: Deploy Query server to PROD
on:
  release:
    types: [released]

jobs:
  PROD_K8S_Query:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 #v4.0.0
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: https://secretsvault.apps.brown.edu
          OP_CONNECT_TOKEN: ${{ secrets.VO_AUTOMATION_CONNECT_TOKEN }}
          PROD_BKEI: op://ozxznermh2dq4gbh55do65oq7e/p3prcq4ibc4ped7hhace22uv7a/prod-bkei.yaml
          ROBOT_PROD: op://ozxznermh2dq4gbh55do65oq7e/rujmiflx3nwpdnjohbmofqvola/password
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0
      -
        name: pull kubeconfig
        run: |
          mkdir -p secrets
          echo "$PROD_BKEI" > secrets/prod-bkei.yaml
          echo "$PROD_BKED" > secrets/prod-bked.yaml
          echo -n "$ROBOT_PROD" > secrets/robot-prod.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build PROD image
        run: make build
      -
        name: Push PROD image
        run: make push.prod
      -
        name: Deploy PROD app
        run: make deploy.prod
