name: Deploy Query server to PROD
on:
  release:
    types: [released]

env:
  VO_RANCH_KUBECONF: ${{ secrets.VO_RANCH_KUBECONF }}
  SCIDMZ_KUBECONF: ${{ secrets.SCIDMZ_KUBECONF }}
  PBKPD_KUBECONF: ${{ secrets.PBKPD_KUBECONF }}
  PBKPI_KUBECONF: ${{ secrets.PBKPI_KUBECONF }}
  QBKPI_KUBECONF: ${{ secrets.QBKPI_KUBECONF }}
  QBKPD_KUBECONF: ${{ secrets.QBKPD_KUBECONF }}
  QSCIDMZ_KUBECONF: ${{ secrets.QSCIDMZ_KUBECONF }}
  QVO_RANCH_KUBECONF: ${{ secrets.QVO_RANCH_KUBECONF }}
  DRBKPD_KUBECONF: ${{ secrets.DRBKPD_KUBECONF }}
  DRBKPI_KUBECONF: ${{ secrets.DRBKPI_KUBECONF }}
  VO_HARBOR_ROBOT: ${{ secrets.VO_HARBOR_ROBOT }}
  VO_UTIL_KUBECONF: ${{ secrets.VO_UTIL_KUBECONF }}

jobs:
  PROD_K8S_Query:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/qa-bkpi.yaml ; echo "$QBKPI_KUBECONF" > secrets/qa-bkpi.yaml
          touch secrets/qa-bkpd.yaml ; echo "$QBKPD_KUBECONF" > secrets/qa-bkpd.yaml
          touch secrets/bkpi.yaml ; echo "$PBKPI_KUBECONF" > secrets/prod-bkpi.yaml
          touch secrets/bkpd.yaml ; echo "$PBKPD_KUBECONF" > secrets/prod-bkpd.yaml
          touch secrets/bkpidr.yaml ; echo "$DRBKPI_KUBECONF" > secrets/dr-bkpi.yaml
          touch secrets/bkpddr.yaml ; echo "$DRBKPD_KUBECONF" > secrets/dr-bkpd.yaml
          touch secrets/qvo-ranch.yaml ; echo "$QVO_RANCH_KUBECONF" > secrets/qa-voranch.yaml
          touch secrets/scidmz-ranch.yaml ; echo "$SCIDMZ_KUBECONF" > secrets/prod-scidmz.yaml
          touch secrets/qscidmz-ranch.yaml ; echo "$QSCIDMZ_KUBECONF" > secrets/qa-scidmz.yaml
          touch secrets/vo-ranch.yaml ; echo "$VO_RANCH_KUBECONF" > secrets/prod-voranch.yaml
          touch secrets/vo-ranch.yaml ; echo "$VO_UTIL_KUBECONF" > secrets/prod-voutil.yaml
          touch secrets/robot.prod ; echo "$VO_HARBOR_ROBOT" > secrets/robot.prod
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build PROD image
        run: make build
      -
        name: Push PROD image
        run: make push.prod
      -
        name: Deploy PROD app
        run: make deploy.prod
