name: Deploy Query server to QA
on:
  push:
    branches:
      - qa
    paths:
      - '**'
      - '!**.md'
      - '!.blackbox/**'

jobs:
  QA_K8S_Query:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3.0
        with:
          version: v1.20.0
      -
        name: Build QA image
        run: make build
      -
        name: Push QA image
        run: make push.qa
      -
        name: Deploy QA app
        run: make deploy.qa
