name: Deploy Query server to QA
on:
  push:
    branches:
      - qa
    paths:
      - '**'
      - '!**.md'
      - '!.blackbox/**'

jobs:
  QA_K8S_Query:
    runs-on: [self-hosted, qa-ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 #v4.0.0
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: https://secretsvault.cis-qas.brown.edu
          OP_CONNECT_TOKEN: ${{ secrets.VO_AUTOMATION_CONNECT_TOKEN }}
          QA_BKEI: op://ozxznermh2dq4gbh55do65oq7e/x6xih2sdzstjcwna4xnhfwyqru/qa-bkei.yaml
          ROBOT_QA: op://ozxznermh2dq4gbh55do65oq7e/faibewfkmurzmth62xm5nxobva/password
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0
      -
        name: pull kubeconfig
        run: |
          mkdir -p secrets
          echo "$QA_BKEI" > secrets/qa-bkei.yaml
          echo "$QA_BKED" > secrets/qa-bked.yaml
          echo -n "$ROBOT_QA" > secrets/robot-qa.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build QA image
        run: make build
      -
        name: Push QA image
        run: make push.qa
      -
        name: Deploy QA app
        run: make deploy.qa
